# Generated by Django 3.2.15 on 2022-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE')], default=1, max_length=10),
        ),
    ]
