# Generated by Django 3.2.15 on 2022-12-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.post'),
        ),
        migrations.AlterField(
            model_name='contend',
            name='Guardian_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Guardian_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='School_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
    ]
