# Generated by Django 3.2.15 on 2022-12-10 17:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_student_guardian_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Guardian_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.guardian'),
            preserve_default=False,
        ),
    ]
