# Generated by Django 3.2.15 on 2022-12-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_guardian_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Guardian_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='School_id',
        ),
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
